// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9o57-mi7JbRKZzThzKvn0sIFqaHvxtw4',
    appId: '1:1072509148760:web:3ce88af87c15a79e08342d',
    messagingSenderId: '1072509148760',
    projectId: 'fujitake-sumaho',
    authDomain: 'fujitake-sumaho.firebaseapp.com',
    storageBucket: 'fujitake-sumaho.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9o57-mi7JbRKZzThzKvn0sIFqaHvxtw4',
    appId: '1:1072509148760:web:f0734f5a7ea1aeb908342d',
    messagingSenderId: '1072509148760',
    projectId: 'fujitake-sumaho',
    authDomain: 'fujitake-sumaho.firebaseapp.com',
    storageBucket: 'fujitake-sumaho.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIPw8UoTVvJ4kxeDerHIrylNSZWOPtwE',
    appId: '1:1072509148760:ios:527e23a87bec71f908342d',
    messagingSenderId: '1072509148760',
    projectId: 'fujitake-sumaho',
    storageBucket: 'fujitake-sumaho.firebasestorage.app',
    iosBundleId: 'com.example.fujitakeApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIPw8UoTVvJ4kxeDerHIrylNSZWOPtwE',
    appId: '1:1072509148760:ios:527e23a87bec71f908342d',
    messagingSenderId: '1072509148760',
    projectId: 'fujitake-sumaho',
    storageBucket: 'fujitake-sumaho.firebasestorage.app',
    iosBundleId: 'com.example.fujitakeApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbAg7G23kcAdX-Ba0odAJlo1iVlpH6fGI',
    appId: '1:1072509148760:android:182144f45c049a7908342d',
    messagingSenderId: '1072509148760',
    projectId: 'fujitake-sumaho',
    storageBucket: 'fujitake-sumaho.firebasestorage.app',
  );

}